### ISSUE TITLE
Inconsistent times

### ISSUE THREAD

**Issue by KermitPurple** [HydroPlume/capstone-tutorfinder#1]
Hi Benjamin,

I looked at your application and it looks great! it's a lot more convenient than the spreadsheets. However, I noticed something that confused me. The times seem to be out of order. The screenshot is provided below. I am using Google Chrome Version 101.0.4951.54 (Official Build) (arm64). I believe all of the information is correct but the rows are just out of order. Great work!

<img width="269" alt="Screen Shot 2022-05-09 at 6 42 53 PM" src="https://user-images.githubusercontent.com/56333467/167525987-e1d0b8fc-3d06-432d-a4ef-167375001353.png">

Best,
Shane McDonough

**Comment by HydroPlume** [comment]
Thanks for submitting this issue;  I've looked into it and the issue appears to be an oddity with the way Chrome implements the `Array.sort()` function.  This may take a little time to figure out, so please be patient.

**Comment by HydroPlume** [comment]
Nevermind, turns out I should pay more attention to the documentation; the `Array.sort()` method relies on a compare function to return (-1, 0, or 1) not true/false.
