### ISSUE TITLE
Update tutors on change

### ISSUE THREAD

**Issue by shanemcdo** [HydroPlume/capstone-tutorfinder#9]
I know I'm making a lot of issues and I'll stop if you want me to.

This one is more of an opinion than a problem. I believe that when the user changes the subject or the number, the board should be updated without the click of a button. I personally find this more user friendly. However, this is just an opinion so feel free to ignore.

**Comment by Hydroidev** [comment]
Duplicate of #8; I love the suggestions, but don't forget to check if your issue has already been submitted!
